module Examples

  def examples
    {
      blinker: [
        ["dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead"],
      ],
      beacon: [
        ["dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "alive", "alive", "dead", "dead", "dead"],
        ["dead", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "dead"],
        ["dead", "dead", "dead", "alive", "alive", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead"],
      ],
      toad: [
        ["dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "alive", "alive", "alive", "dead"],
        ["dead", "alive", "alive", "alive", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead"],
      ],
      pulsar: [
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "alive", "dead", "dead", "dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
      ],
      pentadecathlon: [
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "dead", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "dead", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "alive", "alive", "alive", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
      ],
      glider: [
        ["dead", "alive", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["alive", "alive", "alive", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
      ],
      lwss: [
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead", "alive", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "alive", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead", "dead", "alive", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "alive", "alive", "alive", "alive", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead", "dead"],
      ],
      block: [
        ["dead", "dead", "dead", "dead"],
        ["dead", "alive", "alive", "dead"],
        ["dead", "alive", "alive", "dead"],
        ["dead", "dead", "dead", "dead"],
      ],
      beehive: [
        ["dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "alive", "alive", "dead", "dead"],
        ["dead", "alive", "dead", "dead", "alive", "dead"],
        ["dead", "dead", "alive", "alive", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead"],
      ],
      loaf: [
        ["dead", "dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "alive", "alive", "dead", "dead"],
        ["dead", "alive", "dead", "dead", "alive", "dead"],
        ["dead", "dead", "alive", "dead", "alive", "dead"],
        ["dead", "dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead", "dead"],
      ],
      boat: [
        ["dead", "dead", "dead", "dead", "dead"],
        ["dead", "alive", "alive", "dead", "dead"],
        ["dead", "alive", "dead", "alive", "dead"],
        ["dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead"],
      ],
      tub: [
        ["dead", "dead", "dead", "dead", "dead"],
        ["dead", "dead", "alive", "dead", "dead"],
        ["dead", "alive", "dead", "alive", "dead"],
        ["dead", "dead", "alive", "dead", "dead"],
        ["dead", "dead", "dead", "dead", "dead"],
      ]
    }
end

end